name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: "Name of the image"
      clean-runner:
        required: false
        type: boolean
        default: false
        description: "Whether to clean the runner before building"
      build-base:
        required: false
        type: boolean
        default: false
        description: "Whether to build base images"
      build-alf-requirements:
        required: false
        type: boolean
        default: false
        description: "Whether to build alf-requirements images"
      build-pyalf-requirements:
        required: false
        type: boolean
        default: false
        description: "Whether to build pyalf-requirements images"
      build-pyalf-full:
        required: false
        type: boolean
        default: false
        description: "Whether to build pyalf-full images"
      build-pyalf-doc:
        required: false
        type: boolean
        default: false
        description: "Whether to build pyalf-doc images"
      build-arm64:
        required: false
        type: boolean
        default: false
        description: "Whether to build for arm64 architecture"
env:
  # REGISTRY_URL: ${{ format('ghcr.io/{0}', github.repository) }}
  REGISTRY_URL: ghcr.io/alf-qmc/alf-container

jobs:
  build:
    name: Build ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Clean runner for Docker builds
        if: ${{ inputs.clean-runner }}
        uses: sctg-development/clean-image-for-docker@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Free space before
        run: df -h
      
      - name: Get date
        id: date
        run: echo "value=$(date --iso-8601=date)" >> $GITHUB_OUTPUT

      - name: Build and push base images
        if: ${{ inputs.build-base }}
        uses: docker/build-push-action@v6
        with:
          context: 01-base-imgs/${{ inputs.name }}
          platforms: linux/amd64${{ inputs.build-arm64 && ',linux/arm64' || '' }}
          push: true
          build-args: |
            REGISTRY_PREFIX=${{ env.REGISTRY_URL }}/
          tags: |
            ${{ env.REGISTRY_URL }}/base-imgs/${{ inputs.name }}:latest
            ${{ env.REGISTRY_URL }}/base-imgs/${{ inputs.name }}:${{ steps.date.outputs.value }}
            ${{ env.REGISTRY_URL }}/base-imgs/${{ inputs.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push alf-requirements images
        if: ${{ inputs.build-alf-requirements }}
        uses: docker/build-push-action@v6
        with:
          context: 02-alf-requirements/${{ inputs.name }}
          platforms: linux/amd64${{ inputs.build-arm64 && ',linux/arm64' || '' }}
          push: true
          build-args: |
            REGISTRY_PREFIX=${{ env.REGISTRY_URL }}/
          tags: |
            ${{ env.REGISTRY_URL }}/alf-requirements/${{ inputs.name }}:latest
            ${{ env.REGISTRY_URL }}/alf-requirements/${{ inputs.name }}:${{ steps.date.outputs.value }}
            ${{ env.REGISTRY_URL }}/alf-requirements/${{ inputs.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push pyalf-requirements images
        if: ${{ inputs.build-pyalf-requirements }}
        uses: docker/build-push-action@v6
        with:
          context: 03-pyalf-requirements/${{ inputs.name }}
          platforms: linux/amd64${{ inputs.build-arm64 && ',linux/arm64' || '' }}
          push: true
          build-args: |
            REGISTRY_PREFIX=${{ env.REGISTRY_URL }}/
          tags: |
            ${{ env.REGISTRY_URL }}/pyalf-requirements/${{ inputs.name }}:latest
            ${{ env.REGISTRY_URL }}/pyalf-requirements/${{ inputs.name }}:${{ steps.date.outputs.value }}
            ${{ env.REGISTRY_URL }}/pyalf-requirements/${{ inputs.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push pyalf-full images
        if: ${{ inputs.build-pyalf-full }}
        uses: docker/build-push-action@v6
        with:
          context: 04-pyalf-full/${{ inputs.name }}
          platforms: linux/amd64${{ inputs.build-arm64 && ',linux/arm64' || '' }}
          push: true
          build-args: |
            REGISTRY_PREFIX=${{ env.REGISTRY_URL }}/
          tags: |
            ${{ env.REGISTRY_URL }}/pyalf-full/${{ inputs.name }}:latest
            ${{ env.REGISTRY_URL }}/pyalf-full/${{ inputs.name }}:${{ steps.date.outputs.value }}
            ${{ env.REGISTRY_URL }}/pyalf-full/${{ inputs.name }}:${{ github.sha }}
            docker.io/alfcollaboration/jupyter-pyalf-full:latest
            ${{ format('docker.io/alfcollaboration/jupyter-pyalf-full:{0}', steps.date.outputs.value) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push pyalf-doc images
        if: ${{ inputs.build-pyalf-doc }}
        uses: docker/build-push-action@v6
        with:
          context: 05-pyalf-doc/${{ inputs.name }}
          platforms: linux/amd64${{ inputs.build-arm64 && ',linux/arm64' || '' }}
          push: true
          build-args: |
            REGISTRY_PREFIX=${{ env.REGISTRY_URL }}/
          tags: |
            ${{ env.REGISTRY_URL }}/pyalf-doc/${{ inputs.name }}:latest
            ${{ env.REGISTRY_URL }}/pyalf-doc/${{ inputs.name }}:${{ steps.date.outputs.value }}
            ${{ env.REGISTRY_URL }}/pyalf-doc/${{ inputs.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Free space after
        run: df -h
