name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      build_dir:
        required: true
        type: string
        description: "Directory to build"
      name:
        required: true
        type: string
        description: "Name of the image"
      push_to_dockerhub:
        required: false
        type: boolean
        default: false
        description: "Whether to push to Docker Hub"
      clean-runner:
        required: false
        type: boolean
        default: false
        description: "Whether to clean the runner before building"
env:
  # REGISTRY_URL: ${{ format('ghcr.io/{0}', github.repository) }}
  REGISTRY_URL: ghcr.io/alf-qmc/alf-container

jobs:
  build:
    name: Build ${{ inputs.distribution }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Clean runner for Docker builds
        if: ${{ inputs.clean-runner }}
        uses: sctg-development/clean-image-for-docker@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Login to Docker Hub
        if: ${{ inputs.push_to_dockerhub }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Free space before
        run: df -h
      
      - name: Get date
        id: date
        run: echo "value=$(date --iso-8601=date)" >> $GITHUB_OUTPUT

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.build_dir }}
          push: true
          build-args: |
            REGISTRY_PREFIX=${{ env.REGISTRY_URL }}/
          tags: |
            ${{ env.REGISTRY_URL }}/${{ inputs.name }}:latest
            ${{ env.REGISTRY_URL }}/${{ inputs.name }}:${{ steps.date.outputs.value }}
            ${{ env.REGISTRY_URL }}/${{ inputs.name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Free space after
        run: df -h
